theme: jekyll-theme-minimal
author:
  name: Oleg Rofman
  logo: images/photo.png
  description: Almaty, Kazakhstan <br>o.rofman (at) mail.ru</br>
links:
  - label: "Email"
  # url: "https://www.linkedin.com/in/oleg-rofman-40153327/"
