# Site Settings
locale: "en-US"
title: "Site Title"

theme: jekyll-theme-minimal
title: Oleg Rofman
logo: images/photo.png
url: "https://www.linkedin.com/in/oleg-rofman-40153327/"
description: Almaty, Kazakhstan <br>o.rofman (at) mail.ru</br>

