theme: jekyll-theme-minimal
title: Oleg Rofman
logo: images/photo.png
description: Almaty, Kazakhstan
show_downloads: false
google_analytics:
    links:
        - label: "View My LinkedIn Profile"
        url: "https://www.linkedin.com/in/oleg-rofman-40153327/"
