theme: jekyll-theme-minimal
title: Oleg Rofman
avatar: <img src="./Images/photo_logo.jpg" alt="hi" class="inline" height="auto" width="32"/>
description: Almaty, Kazakhstan <br> o.rofman@mail.ru </br>
