theme: jekyll-theme-minimal
title: Oleg Rofman
logo: images/photo.png
linkedin: https://www.linkedin.com/in/oleg-rofman-40153327/
description: Almaty, Kazakhstan <br> o.rofman@mail.ru </br>
email: o.rofman (at) mail.ru
