theme: jekyll-theme-minimal
minimal_mistakes_skin: "air"
title: Oleg Rofman
logo: images/photo.png
<br></br>
description: Almaty, Kazakhstan <br>o.rofman (at) mail.ru</br>
show_downloads: false
google_analytics:
