title: Oleg Rofman
logo: images/photo.png
description: Almaty, Kazakhstan
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
<a href="https://www.linkedin.com/in/oleg-rofman-40153327/">View My LinkedIn Profile </a></p>
