theme: jekyll-theme-minimal
theme-minimal_skin: "air"
title: Oleg Rofman
logo: images/photo.png
description: <p></p>Almaty, Kazakhstan <br>o.rofman (at) mail.ru</br>
show_downloads: false
google_analytics:
