theme: jekyll-theme-minimal
minimal_mistakes_skin: "air"
title: Oleg Rofman
logo: images/photo.png
description: Almaty, Kazakhstan
email: o.rofman (at) mail.ru
linkedin: https://www.linkedin.com/in/oleg-rofman-40153327/
