theme: jekyll-theme-minimal
title: Oleg Rofman
logo: images/photo.png
description: Almaty, Kazakhstan <br>o.rofman (at) mail.ru</br>
external_navigation:
  - url: https://https://www.linkedin.com/in/oleg-rofman-40153327
    title: "View My LinkedIn Profile"
