theme: jekyll-theme-minimal
minimal_mistakes_skin: "air"
title: Oleg Rofman
logo: images/photo.png
description: Almaty, Kazakhstan <br> o.rofman@mail.ru </br>
email: o.rofman (at) mail.ru
linkedin: oleg-rofman-40153327
