theme: jekyll-theme-minimal
title: Oleg Rofman
<img src="Images/photo-logo.jpg" alt="hi" class="inline" height="auto" width="200" style="border-radius:50%"/>
description: Almaty, Kazakhstan <br> o.rofman@mail.ru </br>
